### Verbo POST - Adicionar
POST http://localhost:8000/cliente/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
  "nome": "Cliente",
  "cpf": "00099988877",
  "telefone": "49988234567",
  "compra_fiado": 1,
  "dia_fiado": 25,
  "senha": "abcbolinhas"
}

### Verbo GET - Listar
GET http://localhost:8000/cliente/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo PUT - Atualiza
PUT http://localhost:8000/cliente/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
  "nome": "Cliente editado",
  "cpf": "12345678910",
  "telefone": "49988234567",
  "compra_fiado": 0,
  "dia_fiado": 0,
  "senha": "bolinhas"
}

### Verbo DELETE - Excluir
DELETE http://localhost:8000/cliente/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
